#!/bin/sh

# Set these paths appropriately

BIN="/home/hvthinh/Downloads/treeTagger/bin"
CMD="/home/hvthinh/Downloads/treeTagger/cmd"
LIB="/home/hvthinh/Downloads/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

