#!/bin/sh

# Set these paths appropriately

BIN="/home/hvthinh/Downloads/treeTagger/bin"
CMD="/home/hvthinh/Downloads/treeTagger/cmd"
LIB="/home/hvthinh/Downloads/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
