#!/bin/sh

# Set these paths appropriately

BIN="/home/hvthinh/Downloads/treeTagger/bin"
CMD="/home/hvthinh/Downloads/treeTagger/cmd"
LIB="/home/hvthinh/Downloads/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
