#!/bin/sh

# Set these paths appropriately

BIN="/home/hvthinh/Downloads/treeTagger/bin"
CMD="/home/hvthinh/Downloads/treeTagger/cmd"
LIB="/home/hvthinh/Downloads/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
